// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CasoModelo.DLL.Data.Models;

public partial class DBCasoModeloContext : DbContext
{
    public DBCasoModeloContext(DbContextOptions<DBCasoModeloContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Componente> Componentes { get; set; }

    public virtual DbSet<DetallesOrden> DetallesOrdens { get; set; }

    public virtual DbSet<OrdenProducion> OrdenesProducions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Componente>(entity =>
        {
            entity.HasKey(e => e.Codigo);

            entity.ToTable("COMPONENTES");

            entity.Property(e => e.Codigo).HasColumnName("CODIGO");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NOMBRE");
        });

        modelBuilder.Entity<DetallesOrden>(entity =>
        {
            entity.HasKey(e => new { e.IdDetalle, e.NroOrden });

            entity.ToTable("DETALLES_ORDEN");

            entity.Property(e => e.IdDetalle).HasColumnName("ID_DETALLE");
            entity.Property(e => e.NroOrden).HasColumnName("NRO_ORDEN");
            entity.Property(e => e.Cantidad).HasColumnName("CANTIDAD");
            entity.Property(e => e.CodComponente).HasColumnName("COD_COMPONENTE");

            entity.HasOne(d => d.CodComponenteNavigation).WithMany(p => p.DetallesOrdens)
                .HasForeignKey(d => d.CodComponente)
                .HasConstraintName("FK_DETALLES_ORDEN_COMPONENTES");

            entity.HasOne(d => d.NroOrdenNavigation).WithMany(p => p.DetallesOrdens)
                .HasForeignKey(d => d.NroOrden)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DETALLES_ORDEN_ORDENES_PRODUCION");
        });

        modelBuilder.Entity<OrdenProducion>(entity =>
        {
            entity.HasKey(e => e.NroOrden);

            entity.ToTable("ORDENES_PRODUCION");

            entity.Property(e => e.NroOrden).HasColumnName("NRO_ORDEN");
            entity.Property(e => e.Cantidad).HasColumnName("CANTIDAD");
            entity.Property(e => e.Estado).HasColumnName("ESTADO");
            entity.Property(e => e.Fecha)
                .HasColumnType("date")
                .HasColumnName("FECHA");
            entity.Property(e => e.Modelo)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("MODELO");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}