// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ejercicio2_7.DLL.Data.Models;

public partial class Turno
{
    public int Id { get; set; }

    public string Fecha { get; set; }

    public string Hora { get; set; }

    public string Cliente { get; set; }

    public virtual ICollection<DetallesTurno> TDetallesTurnos { get; set; } = new List<DetallesTurno>();
}