CREATE DATABASE DB_CASO_MODELO
GO
USE DB_CASO_MODELO
GO

CREATE TABLE ORDENES_PRODUCION
(
	NRO_ORDEN INT IDENTITY(1,1),
	FECHA DATE,
	MODELO VARCHAR(50),
	CANTIDAD INT,
	ESTADO BIT
	CONSTRAINT PK_ORDENES_PRODUCION PRIMARY KEY (NRO_ORDEN)
)

CREATE TABLE COMPONENTES
(
	CODIGO INT IDENTITY(1,1),
	NOMBRE VARCHAR(50)
	CONSTRAINT PK_COMPONENTES PRIMARY KEY (CODIGO)
)

CREATE TABLE DETALLES_ORDEN
(
	ID_DETALLE INT,
	NRO_ORDEN INT,
	COD_COMPONENTE INT,
	CANTIDAD INT,
	CONSTRAINT PK_DETALLES_ORDEN PRIMARY KEY (ID_DETALLE,NRO_ORDEN),
	CONSTRAINT FK_DETALLES_ORDEN_ORDENES_PRODUCION FOREIGN KEY (NRO_ORDEN)
		REFERENCES ORDENES_PRODUCION (NRO_ORDEN),
	CONSTRAINT FK_DETALLES_ORDEN_COMPONENTES FOREIGN KEY (COD_COMPONENTE)
		REFERENCES COMPONENTES (CODIGO)
)

INSERT INTO COMPONENTES (NOMBRE) VALUES 
('Motor'),
('Chasis'),
('Rueda');

INSERT INTO ORDENES_PRODUCION (FECHA, MODELO, CANTIDAD, ESTADO) VALUES 
('2024-10-01', 'Modelo A', 100, 1),
('2024-10-02', 'Modelo B', 200, 0),
('2024-10-03', 'Modelo C', 150, 1),
('2024-10-04', 'Modelo D', 120, 0),
('2024-10-05', 'Modelo E', 180, 1);

INSERT INTO DETALLES_ORDEN (ID_DETALLE, NRO_ORDEN, COD_COMPONENTE, CANTIDAD) VALUES 
(1, 1, 1, 50),  -- Orden 1, 50 Motores
(2, 1, 2, 30),  -- Orden 1, 30 Chasis
(1, 2, 3, 200), -- Orden 2, 200 Ruedas
(1, 3, 1, 70),  -- Orden 3, 70 Motores
(2, 3, 2, 60),  -- Orden 3, 60 Chasis
(3, 3, 3, 150), -- Orden 3, 150 Ruedas
(1, 4, 1, 40),  -- Orden 4, 40 Motores
(1, 5, 2, 90);  -- Orden 5, 90 Chasis


select * from ORDENES_PRODUCION
select * from DETALLES_ORDEN order by NRO_ORDEN, ID_DETALLE