// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CasoModelo.DLL.Data.Models;

public partial class DetallesOrden
{
    public int IdDetalle { get; set; }

    public int NroOrden { get; set; }

    public int? CodComponente { get; set; }

    public int? Cantidad { get; set; }

    [JsonIgnore]
    public virtual Componente CodComponenteNavigation { get; set; }
    [JsonIgnore]
    public virtual OrdenProducion NroOrdenNavigation { get; set; }
}