// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CasoModelo.DLL.Data.Models;

public partial class OrdenProducion
{
    public int NroOrden { get; set; }

    public DateTime? Fecha { get; set; }

    public string Modelo { get; set; }

    public int? Cantidad { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<DetallesOrden> DetallesOrdens { get; set; } = new List<DetallesOrden>();
}