// <auto-generated />
using Ejercicio2_7.DLL.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejercicio2_7.DLL.Migrations
{
    [DbContext(typeof(DB_TURNOSContext))]
    [Migration("20241008162853_TurnoServicioExtraProps")]
    partial class TurnoServicioExtraProps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejercicio2_7.DLL.Data.Models.DetallesTurno", b =>
                {
                    b.Property<int>("IdTurno")
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdTurno", "IdServicio");

                    b.HasIndex("IdServicio");

                    b.ToTable("T_DETALLES_TURNO", (string)null);
                });

            modelBuilder.Entity("Ejercicio2_7.DLL.Data.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Costo")
                        .HasColumnType("int")
                        .HasColumnName("costo");

                    b.Property<string>("EnPromocion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("enPromocion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("T_SERVICIOS", (string)null);
                });

            modelBuilder.Entity("Ejercicio2_7.DLL.Data.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cliente");

                    b.Property<string>("Fecha")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fecha");

                    b.Property<string>("FechaBaja")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("FechaBaja");

                    b.Property<string>("Hora")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("hora");

                    b.Property<string>("MotivoBaja")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MotivoBaja");

                    b.HasKey("Id");

                    b.ToTable("T_TURNOS", (string)null);
                });

            modelBuilder.Entity("Ejercicio2_7.DLL.Data.Models.DetallesTurno", b =>
                {
                    b.HasOne("Ejercicio2_7.DLL.Data.Models.Servicio", "IdServicioNavigation")
                        .WithMany("TDetallesTurnos")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK_T_DETALLES_TURNOS_SERVICIOS");

                    b.HasOne("Ejercicio2_7.DLL.Data.Models.Turno", "IdTurnoNavigation")
                        .WithMany("TDetallesTurnos")
                        .HasForeignKey("IdTurno")
                        .IsRequired()
                        .HasConstraintName("FK_T_DETALLES_TURNOS_TURNO");

                    b.Navigation("IdServicioNavigation");

                    b.Navigation("IdTurnoNavigation");
                });

            modelBuilder.Entity("Ejercicio2_7.DLL.Data.Models.Servicio", b =>
                {
                    b.Navigation("TDetallesTurnos");
                });

            modelBuilder.Entity("Ejercicio2_7.DLL.Data.Models.Turno", b =>
                {
                    b.Navigation("TDetallesTurnos");
                });
#pragma warning restore 612, 618
        }
    }
}
