// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Clase24_09.DLL.Entities.Models;

public partial class Turno
{
    public int Id { get; set; }

    public string Fecha { get; set; }

    public string Hora { get; set; }

    public string Cliente { get; set; }

}